name: Test Against Repos

on: [push, pull_request]

jobs:
  Integration_Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos: [
          {name: 'haus.gg', repository: 'EvHaus/haus.gg'},
          {name: 'globexdesigns.com', repository: 'GlobexDesignsInc/globexdesigns.com'}
        ]

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        node-version: '18'

    - name: Install dependencies
      run: pnpm install
    
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        path: ${{ matrix.repos.name }}
        repository: ${{ matrix.repos.repository }}
    
    - name: Install repo dependencies with link
      run: pnpm install && mv ${{ matrix.repos.name }} ../ && cd ../${{ matrix.repos.name }} && pnpm link ../eslint-config-globex --all
    
    - name: Run eslint
      run: cd ../${{ matrix.repos.name }} && pnpm eslint
