
name: Test Against Repos

on: [push, pull_request]

jobs:
  Integration_Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos: [
          {name: 'haus.gg', repository: 'EvHaus/haus.gg'},
          {name: 'globexdesigns.com', repository: 'GlobexDesignsInc/globexdesigns.com'}
        ]

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        node-version: '18'

    - name: Install dependencies
      run: pnpm i --no-frozen-lockfile
    
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        path: ${{ matrix.repos.name }}
        repository: ${{ matrix.repos.repository }}
    
    - name: Install repo
      run: |
        # Can't install into cwd otherwise pnpm doesn't create node_modules
        mv ${{ matrix.repos.name }} ../
        cd ../${{ matrix.repos.name }}
        pnpm i --frozen-lockfile

        # Manually symlink relevant node_modules to repo until
        # https://github.com/pnpm/pnpm/issues/3026 is resolved
        cd node_modules
        # ln -sf doesn't work, so we have to delete first
        rm -rf @eslint-config-globex
        rm -rf eslint-config-globex
        ln -s ../../eslint-config-globex/packages @eslint-config-globex
        ln -s ../../eslint-config-globex/packages/core eslint-config-globex
    
    - name: Run eslint
      run: cd ../${{ matrix.repos.name }} && pnpm eslint
