name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        cache: 'yarn'
        node-version: 'lts/*'

    - name: Install dependencies
      run: yarn install --pure-lockfile
    
    - name: Test
      run: yarn test
