name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8.6.0
    
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        node-version: '20'

    - name: Install dependencies
      run: pnpm i --no-frozen-lockfile
    
    - name: Test
      run: pnpm test

  Release:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8.6.0

    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        node-version: '20'

    - name: Install dependencies
      run: pnpm i

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm semantic-release