name: Test & Release

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        node-version: 'lts/*'

    - name: Install dependencies
      run: yarn install
    
    - name: Test
      run: yarn test

  Release:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        node-version: 'lts/*'

    - name: Install dependencies
      run: yarn install

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
