name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install
      run: yarn install
    
    - name: Test
      run: yarn test
